/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as MarcaSlugRouteImport } from './routes/marca.$slug'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminPremiumRouteImport } from './routes/admin.premium'
import { Route as AdminPaginasRouteImport } from './routes/admin.paginas'
import { Route as AdminOrcamentosRouteImport } from './routes/admin.orcamentos'
import { Route as AdminMidiaRouteImport } from './routes/admin.midia'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminMarcasRouteImport } from './routes/admin.marcas'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminFooterRouteImport } from './routes/admin.footer'
import { Route as AdminEmpresaRouteImport } from './routes/admin.empresa'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminProdutosIndexRouteImport } from './routes/admin.produtos.index'
import { Route as AdminProdutosBrandRouteImport } from './routes/admin.produtos.$brand'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcaSlugRoute = MarcaSlugRouteImport.update({
  id: '/marca/$slug',
  path: '/marca/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPremiumRoute = AdminPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaginasRoute = AdminPaginasRouteImport.update({
  id: '/paginas',
  path: '/paginas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrcamentosRoute = AdminOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMidiaRoute = AdminMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarcasRoute = AdminMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFooterRoute = AdminFooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmpresaRoute = AdminEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosIndexRoute = AdminProdutosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProdutosRoute,
} as any)
const AdminProdutosBrandRoute = AdminProdutosBrandRouteImport.update({
  id: '/$brand',
  path: '/$brand',
  getParentRoute: () => AdminProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/empresa': typeof AdminEmpresaRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/paginas': typeof AdminPaginasRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/marca/$slug': typeof MarcaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/$brand': typeof AdminProdutosBrandRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/empresa': typeof AdminEmpresaRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/paginas': typeof AdminPaginasRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/marca/$slug': typeof MarcaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/produtos/$brand': typeof AdminProdutosBrandRoute
  '/admin/produtos': typeof AdminProdutosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/sobre': typeof SobreRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/empresa': typeof AdminEmpresaRoute
  '/admin/footer': typeof AdminFooterRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/paginas': typeof AdminPaginasRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/produtos': typeof AdminProdutosRouteWithChildren
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/marca/$slug': typeof MarcaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/produtos/$brand': typeof AdminProdutosBrandRoute
  '/admin/produtos/': typeof AdminProdutosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/contato'
    | '/login'
    | '/sobre'
    | '/admin/banners'
    | '/admin/empresa'
    | '/admin/footer'
    | '/admin/home'
    | '/admin/leads'
    | '/admin/marcas'
    | '/admin/marketing'
    | '/admin/menu'
    | '/admin/midia'
    | '/admin/orcamentos'
    | '/admin/paginas'
    | '/admin/premium'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/marca/$slug'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/produtos/$brand'
    | '/admin/produtos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/contato'
    | '/login'
    | '/sobre'
    | '/admin/banners'
    | '/admin/empresa'
    | '/admin/footer'
    | '/admin/home'
    | '/admin/leads'
    | '/admin/marcas'
    | '/admin/marketing'
    | '/admin/menu'
    | '/admin/midia'
    | '/admin/orcamentos'
    | '/admin/paginas'
    | '/admin/premium'
    | '/admin/usuarios'
    | '/marca/$slug'
    | '/produto/$slug'
    | '/admin'
    | '/admin/produtos/$brand'
    | '/admin/produtos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/contato'
    | '/login'
    | '/sobre'
    | '/admin/banners'
    | '/admin/empresa'
    | '/admin/footer'
    | '/admin/home'
    | '/admin/leads'
    | '/admin/marcas'
    | '/admin/marketing'
    | '/admin/menu'
    | '/admin/midia'
    | '/admin/orcamentos'
    | '/admin/paginas'
    | '/admin/premium'
    | '/admin/produtos'
    | '/admin/usuarios'
    | '/marca/$slug'
    | '/produto/$slug'
    | '/admin/'
    | '/admin/produtos/$brand'
    | '/admin/produtos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRoute
  SobreRoute: typeof SobreRoute
  MarcaSlugRoute: typeof MarcaSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marca/$slug': {
      id: '/marca/$slug'
      path: '/marca/$slug'
      fullPath: '/marca/$slug'
      preLoaderRoute: typeof MarcaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/premium': {
      id: '/admin/premium'
      path: '/premium'
      fullPath: '/admin/premium'
      preLoaderRoute: typeof AdminPremiumRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paginas': {
      id: '/admin/paginas'
      path: '/paginas'
      fullPath: '/admin/paginas'
      preLoaderRoute: typeof AdminPaginasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orcamentos': {
      id: '/admin/orcamentos'
      path: '/orcamentos'
      fullPath: '/admin/orcamentos'
      preLoaderRoute: typeof AdminOrcamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/midia': {
      id: '/admin/midia'
      path: '/midia'
      fullPath: '/admin/midia'
      preLoaderRoute: typeof AdminMidiaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marcas': {
      id: '/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AdminMarcasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/footer': {
      id: '/admin/footer'
      path: '/footer'
      fullPath: '/admin/footer'
      preLoaderRoute: typeof AdminFooterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/empresa': {
      id: '/admin/empresa'
      path: '/empresa'
      fullPath: '/admin/empresa'
      preLoaderRoute: typeof AdminEmpresaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos/': {
      id: '/admin/produtos/'
      path: '/'
      fullPath: '/admin/produtos/'
      preLoaderRoute: typeof AdminProdutosIndexRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
    '/admin/produtos/$brand': {
      id: '/admin/produtos/$brand'
      path: '/$brand'
      fullPath: '/admin/produtos/$brand'
      preLoaderRoute: typeof AdminProdutosBrandRouteImport
      parentRoute: typeof AdminProdutosRoute
    }
  }
}

interface AdminProdutosRouteChildren {
  AdminProdutosBrandRoute: typeof AdminProdutosBrandRoute
  AdminProdutosIndexRoute: typeof AdminProdutosIndexRoute
}

const AdminProdutosRouteChildren: AdminProdutosRouteChildren = {
  AdminProdutosBrandRoute: AdminProdutosBrandRoute,
  AdminProdutosIndexRoute: AdminProdutosIndexRoute,
}

const AdminProdutosRouteWithChildren = AdminProdutosRoute._addFileChildren(
  AdminProdutosRouteChildren,
)

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminEmpresaRoute: typeof AdminEmpresaRoute
  AdminFooterRoute: typeof AdminFooterRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminMarcasRoute: typeof AdminMarcasRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminMidiaRoute: typeof AdminMidiaRoute
  AdminOrcamentosRoute: typeof AdminOrcamentosRoute
  AdminPaginasRoute: typeof AdminPaginasRoute
  AdminPremiumRoute: typeof AdminPremiumRoute
  AdminProdutosRoute: typeof AdminProdutosRouteWithChildren
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminEmpresaRoute: AdminEmpresaRoute,
  AdminFooterRoute: AdminFooterRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminMarcasRoute: AdminMarcasRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminMidiaRoute: AdminMidiaRoute,
  AdminOrcamentosRoute: AdminOrcamentosRoute,
  AdminPaginasRoute: AdminPaginasRoute,
  AdminPremiumRoute: AdminPremiumRoute,
  AdminProdutosRoute: AdminProdutosRouteWithChildren,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRoute,
  SobreRoute: SobreRoute,
  MarcaSlugRoute: MarcaSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
